on: push
name: Node Build, Package & Publish
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #- name: npm install and npm run build
       # run: |
        #  npm i
         # npm run build
      - name: Login to Podman
        id: login
        run:  |
          podman login docker.pkg.github.com -u afu174 -p ${{ secrets.GITHUB_TOKEN }}
          
      - name: use vars
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"
          echo "Sha: ${{ steps.vars.outputs.repo }}"
